### PR TITLE
update data.csv. add data-extant.csv.

### PR DESCRIPTION
**Pull request by terramare**
Updated `data.csv` through March 2015. Added subset called `data.extant.csv`, which only includes current browsers. Removed `views` section of `datapackage.json`, as it did not seem to fit provided dataset.

### CODE REVIEW

**Comment by rgrp** [comment]
@terramare views was working before - could you see if we could fix rather than removing?

Also re file naming would it be possible to have data-extant.csv (as good practice not to have '.' in actual file name other than as separating extension)

**Comment by terramare** [comment]
@rgrp Ah, I was not aware of the recline integration. That is cool. When I try to point the Data Package Viewer to the current browser-stats dataset, it doesn't get past "Loading View". Can you help me understand why this may be and then I will incorporate it into my changes.

Also, my comment above misspelled the true filename of the new csv, it is indeed `data-extant.csv`.

**Comment by rgrp** [comment]
@terramare good question. Looking at code this seems to be an issue in the naming of the column "Moz (All)" - either recline has got stricter on column names or we used to have a nicer column name. I think if column were named "Moz-All" it would work fine so maybe we rename that column.

**Comment by terramare** [comment]
@rgrp I actually removed Moz (All) from the recline graph since it equates to Firefox for over seven years now.

**Comment by terramare** [comment]
@rgrp I squashed my commits. dataset now updated through April 2015. date format changed to yyyy-mm. [DataPackage Viewer](http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fterramare%2Fbrowser-stats) graph is now drawing properly. please let me know if you would like to see any other changes.

**Comment by rgrp** [comment]
Fantastic and great work - thank-you! And if you are interested in becoming the ongoing maintainer let me know!

**Pull request merged**
